name: Lidar Benchmark
on: [pull_request]
jobs:
  benchmark-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t benchmark .
      - name: Run Benchmark in Docker container
        run: docker run --rm -v $(pwd):/app benchmark
      - name: Report to PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const result = fs.readFileSync('./output.txt', 'utf-8')
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `### Command Results\n\`\`\`\n${result}\n\`\`\``,
            });
